network:
  ethernet:
    ip: "192.168.1.101"
    gateway: "192.168.1.1"
  wifi:
    ssid: "your_wifi_ssid"
    password: "your_wifi_password"
    ip: "192.168.1.102"
    gateway: "192.168.1.1"

sensors:
  sensor1: "SparkFun AS7263 NIR"
  sensor2: "SparkFun Triad AS7265x - Unit 1"
  sensor3: "SparkFun Triad AS7265x - Unit 2"

aws:
  iot_core_endpoint: "your_aws_iot_core_endpoint"
  greengrass_group: "your_greengrass_group"
  iot_topic: "iot/pi1/data"
  cert_path: "/certs/certificate.pem.crt"
  key_path: "/certs/private.pem.key"
  ca_path: "/certs/AmazonRootCA1.pem"

logging:
  log_file: "logs/pi1_logs.log"
