system:
  enable_camera: false
  enable_sensors: true
  enable_logging: true
  enable_greengrass: true
  enable_aws: true
  enable_mqtt: true
  enable_network_monitoring: true
  enable_relay_controller: true
  enable_alert_manager: true
  enable_debug: false
  enable_json_logging: true
  conveyor_speed: 300  # Velocidad del conveyor en pulgadas/segundo

# 16 pulgadas/seg (40 cm/seg) en ajustes más lentos.
# 120 pulgadas/seg (300 cm/seg) en ajustes más rápidos.

delays:
  camera_to_sensor: 12  # Distancia entre la cámara y los sensores en pulgadas
  sensor_to_valve_1: 21  # Distancia entre los sensores y la válvula 1 en pulgadas
  sensor_to_valve_2: 27  # Distancia entre los sensores y la válvula 2 en pulgadas

relays:
  - mux_channel: 0       # Canal del MUX para el relé 1
    i2c_address: 0x18    # Dirección I2C del relé 1
    assigned_valve: "Valve 1 (PET)"
  - mux_channel: 1       # Canal del MUX para el relé 2
    i2c_address: 0x18    # Dirección I2C del relé 2
    assigned_valve: "Valve 2 (HDPE)"
  
network:
  ping_host: "8.8.8.8"
  check_interval: 10
  ethernet:
    interface: "eth0"             # Interfaz de red Ethernet
    ip: "192.168.1.137"           # Dirección IP estática para Ethernet
    gateway: "192.168.1.1"        # Puerta de enlace para Ethernet
  wifi:
    interface: "wlan0"            # Interfaz de red Wi-Fi
    ssid: "Capstone"              # Nombre de la red Wi-Fi
    password: "Elefante"          # Contraseña de la red Wi-Fi
    ip: "192.168.2.11"            # Dirección IP estática para Wi-Fi
    gateway: "192.168.2.1"        # Puerta de enlace para Wi-Fi

mqtt:
  enable_mqtt: true
  auto_reconnect: true
  enable_aws: false
  broker_addresses:
    - "192.168.1.147"
    - "192.168.2.147"
  port: 1883
  keepalive: 60
  client_id: "Raspberry-2"
  topics:
    action: "valvula/accion"
    status: "valvula/estado"
    alertas: "raspberry-2/alertas"

i2c:
  bus: 1

sensors:
  pressure:
    addresses: [0x28, 0x29, 0x2A, 0x2B]

valves:
  relay_pins: [17, 27]

simulation:
  detection_interval: 5                                         # Intervalo de tiempo para detectar un cambio en el estado de la válvula
  detection_delay: 3                                            # Delay entre recepción del mensaje y activación del relé

logging:
  log_file: "/home/raspberry-2/logs/pi2_logs.log"               # Archivo de logs para registrar las operaciones
  error_log_file: "/home/raspberry-2/logs/pi2_error_logs.log"   # Logs de errores
  max_size_mb: 5                                                # Tamaño máximo del archivo de logs en MB
  backup_count: 5                                               # Número de archivos de logs de respaldo
  alert_log_file: "logs/alerts.json"
  rotate_alert_logs: true
  enable_debug: false

mux:
  relays:
    - {mux_channel: 0, i2c_address: 0x18}  # Relay 1 (PET)
    - {mux_channel: 1, i2c_address: 0x18}  # Relay 2 (HDPE)

greengrass:
  enable_greengrass: true
  region: "us-east-1"