system:
  enable_camera: false
  enable_sensors: true
  enable_logging: true
  enable_greengrass: true
  enable_aws: true
  enable_mqtt: true
  enable_network_monitoring: true
  enable_relay_controller: true
  enable_alert_manager: true
  enable_debug: false
  enable_json_logging: true

network:
  ping_host: "8.8.8.8"
  check_interval: 10
  ethernet:
    interface: "eth0" 
    ip: "192.168.1.147"           # Dirección IP estática para Ethernet
    gateway: "192.168.1.1"        # Puerta de enlace para Ethernet
  wifi:
    interface: "wlan0"
    ssid: "Capstone"              # Nombre de la red Wi-Fi
    password: "Elefante"          # Contraseña de la red Wi-Fi
    ip: "192.168.2.147"            # Dirección IP estática para Wi-Fi
    gateway: "192.168.2.1"        # Puerta de enlace para Wi-Fi

mqtt:
  enable_mqtt: true
  auto_reconnect: true
  enable_aws: false
  broker_addresses: "localhost"
  port: 1883
  keepalive: 60
  client_id: "Raspberry-3"
  topics:
    entry: "material/entrada"
    detection: "material/deteccion"
    action: "valvula/accion"
    status: "valvula/estado"
    alertas: "raspberry-3/alertas"

i2c:
  bus: 1

sensors:
  weight:
    addresses: [0x2C, 0x2D]

camera:
  port: 0

aws:
  credentials:
    access_key_id: "tu_access_key_id"
    secret_access_key: "tu_secret_access_key"
  region: "tu_region"
  iot_endpoint: "tu_endpoint_de_iot"

simulation:
  duration: 3600                                                  # Duración total de la simulación en segundos
  detection_interval: 5                                         # Intervalo en segundos entre detecciones de material

communication:
  delay_to_pi1: 2                                               # Tiempo de espera en segundos entre Raspberry Pi 3 y Raspberry Pi 1

logging:
  log_file: "/home/raspberry-3/logs/pi3_logs.log"               # Archivo de logs para registrar las operaciones
  error_log_file: "/home/raspberry-3/logs/pi3_error_logs.log"   # Logs de errores
  max_size_mb: 5                                                # Tamaño máximo del archivo de logs en MB
  backup_count: 5 
  alert_log_file: "logs/alerts.json"
  rotate_alert_logs: true
  enable_debug: false       

greengrass:
  enable_greengrass: true
  region: "us-east-1"                                       # Número de archivos de logs de respaldo
