# Configuración específica para Raspberry Pi 1

system:
  enable_camera: false                # Raspberry Pi #1 no tiene cámara
  enable_sensors: true                # Sensores espectroscópicos AS7265x habilitados
  enable_sensor_leds: false           # Apagar LEDs de los sensores AS7265x
  enable_touch_screen: false          # No aplica a Raspberry Pi #1
  enable_mqtt: true                   # MQTT habilitado
  enable_greengrass: true             # AWS Greengrass habilitado
  enable_aws: true                    # Conexión a AWS habilitada
  enable_logging: true                # Logs habilitados
  enable_sensor_diagnostics: true     # Diagnósticos de sensores habilitados
  enable_mux_diagnostics: true        # Diagnósticos del MUX habilitados
  enable_auto_restart: false           # Reinicio automático habilitado
  enable_network_monitoring: true     # Monitoreo de red habilitado
  enable_detailed_logging: true       # Nivel detallado de logs
  enable_power_saving: true           # Modo de ahorro de energía
  metrics_interval: 60                # Intervalo de métricas en segundos
  processing_time_alert_ms: 500       # Tiempo máximo de procesamiento en milisegundos
  diagnostics_interval: 300           # Intervalo de diagnósticos en segundos
  max_retries: 3                      # Número máximo de reintentos

network:
  ethernet:
    ip: "192.168.1.145"           # Dirección IP estática para Ethernet
    gateway: "192.168.1.1"        # Puerta de enlace para Ethernet
  wifi:
    ssid: "Capstone"              # Nombre de la red Wi-Fi
    password: "Elefante"          # Contraseña de la red Wi-Fi
    ip: "192.168.2.145"           # Dirección IP estática para Wi-Fi
    gateway: "192.168.2.1"        # Puerta de enlace para Wi-Fi

# Configuración del MUX
mux:
  i2c_address: 0x70                   # Dirección I2C del MUX
  i2c_bus: 1                          # Bus I2C donde está conectado el MUX
  channels:                           # Canales asignados al MUX
    - id: 0                           # ID del canal físico en el MUX
      sensor_name: "AS7265x_1"        # Nombre del sensor conectado
      description: "Sensor espectroscópico principal"
      enabled: true                   # Habilitar/deshabilitar este canal
    - id: 4
      sensor_name: "AS7265x_2"
      description: "Sensor espectroscópico secundario"
      enabled: true
    - id: 7
      sensor_name: "AS7265x_3"
      description: "Sensor espectroscópico terciario"
      enabled: true

# Configuración de los sensores
sensors:
  default_settings:                   # Configuraciones comunes para todos los sensores
    integration_time: 100             # Tiempo de integración en ms
    gain: 3                           # Ganancia (0: 1x, 1: 3.7x, 2: 16x, 3: 64x)
    led_intensity: 128                # Intensidad de los LEDs (0-255)
    read_interval: 1                  # Intervalo de lectura en segundos
    enable_interrupts: true           # Habilitar interrupciones
    operating_mode: 0                 # Modo de operación (0=Normal, 1=Esclavo, etc.)
  as7265x:                            # Configuración específica para sensores AS7265x
    channels:                         # Asociación directa con los canales del MUX
      - channel: 0                    # Canal en el MUX
        name: "AS7265x_1"             # Nombre del sensor
        integration_time: 150         # Tiempo de integración en ms (sobrescribe el predeterminado)
        gain: 2                       # Ganancia (sobrescribe el predeterminado)
        led_intensity: 100            # Intensidad del LED (sobrescribe el predeterminado)
        read_interval: 2              # Intervalo de lectura en segundos (sobrescribe el predeterminado)
        spectral_resolution: "high"   # Resolución espectral high, medium, low
        enable_interrupts: false      # Deshabilitar interrupciones
        operating_mode: 1             # Modo de operación del sensor (1=Continuo)
        enabled: true                 # Habilitar/deshabilitar este sensor
      - channel: 4                    # Canal en el MUX
        name: "AS7265x_2"             # Nombre del sensor
        integration_time: 100         # Tiempo de integración en ms
        gain: 3                       # Ganancia
        led_intensity: 128            # Intensidad del LED
        read_interval: 1              # Intervalo de lectura en segundos
        spectral_resolution: "high" # Resolución espectral
        enable_interrupts: true       # Habilitar interrupciones
        operating_mode: 0             # Modo de operación
        enabled: true                 # Habilitar/deshabilitar este sensor
      - channel: 7                    # Canal en el MUX
        name: "AS7265x_3"             # Nombre del sensor
        integration_time: 120         # Tiempo de integración en ms
        gain: 1                       # Ganancia
        led_intensity: 255            # Intensidad del LED
        read_interval: 1              # Intervalo de lectura en segundos
        spectral_resolution: "high"    # Resolución espectral
        enable_interrupts: true       # Habilitar interrupciones
        operating_mode: 0             # Modo de operación
        enabled: true                 # Habilitar/deshabilitar este sensor

# Configuración avanzada
advanced_settings:
  diagnostics_interval: 300           # Intervalo de diagnósticos en segundos
  metrics_interval: 60                # Intervalo de envío de métricas en segundos
  critical_temperature: 85            # Temperatura crítica en °C para el sensor
  power_saving: true                  # Activar modo de ahorro de energía

greengrass:
  group_name: "Capstone-Group"   # Nombre del grupo de Greengrass
  functions:
    - name: "DetectPlasticType"   # Nombre de la función Lambda local
      arn: "arn:aws:lambda:region:account-id:function:DetectPlasticType"

aws:
  region: "us-east-1"                             # Cambia según tu región
  iot_core_endpoint: "your_aws_iot_core_endpoint" # Endpoint de AWS IoT Core
  iot_topics:
    sensor_data: "raspberry-1/sensor_data"                # Tópico para enviar datos de los sensores
    settings_update: "raspberry-1/settings_update"        # Tópico para recibir actualizaciones de configuración
  cert_path: "/certs/certificate.pem.crt"         # Certificado del cliente
  key_path: "/certs/private.pem.key"              # Llave privada
  ca_path: "/certs/AmazonRootCA1.pem"             # Certificado raíz de Amazon

mqtt:
  broker_address: 
  - "192.168.1.147"                               # Dirección IP del broker MQTT local (Ethernet Raspberry Pi #3)
  - "192.168.2.147"                               # Dirección IP del broker MQTT local (Wi-Fi Raspberry Pi #3)
  port: 1883                                      # Puerto del broker MQTT
  username: "raspberry-1"                                  # Usuario para el broker local
  password: "Elefante"                       # Contraseña para el broker local
  topics:
    sensor_data: "raspberry-1/sensor_data"                # Tópico para publicar datos de sensores
    settings_update: "raspberry-1/settings_update"        # Tópico para recibir actualizaciones de configuración
    alerts: "raspberry-1/alerts"                          # Tópico para enviar alertas

plastic_thresholds:
  # PET (Polietileno Tereftalato): Común en botellas plásticas transparentes. 
  # Características: Fuertes picos en UV y azul, absorbe menos en el infrarrojo.
  PET:
    - [100, 200]  # Rango espectral aproximado para el canal 1
    - [150, 250]  # Rango espectral aproximado para el canal 2
    - [50, 100]   # Rango espectral aproximado para el canal 3

  # HDPE (Polietileno de Alta Densidad): Usado en envases opacos como botellas de leche.
  # Características: Alta reflexión en el infrarrojo cercano.
  HDPE:
    - [200, 300]  # Canal 1 (picos en infrarrojo cercano)
    - [250, 350]  # Canal 2
    - [100, 150]  # Canal 3

  # LDPE (Polietileno de Baja Densidad): Bolsas plásticas y películas.
  # Características: Absorción moderada en UV, con menor intensidad que HDPE.
  LDPE:
    - [50, 150]   # Canal 1
    - [100, 200]  # Canal 2
    - [150, 250]  # Canal 3

  # PP (Polipropileno): Tapas de botellas y envases de alimentos.
  # Características: Moderada absorción en UV y azul, menos notable en verde.
  PP:
    - [80, 180]   # Canal 1
    - [120, 220]  # Canal 2
    - [60, 120]   # Canal 3

  # PS (Poliestireno): Vasos desechables y materiales de embalaje.
  # Características: Picos notables en azul y verde, absorbe menos en amarillo.
  PS:
    - [90, 190]   # Canal 1
    - [110, 210]  # Canal 2
    - [70, 130]   # Canal 3

  # PVC (Policloruro de Vinilo): Tubos, ventanas, y empaques.
  # Características: Fuertes picos en azul y amarillo.
  PVC:
    - [130, 230]  # Canal 1
    - [180, 280]  # Canal 2
    - [100, 200]  # Canal 3

  # Otros: Compuestos de plástico mezclado o no identificados.
  # Características: Firmas espectrales variadas, valores genéricos.
  Otros:
    - [70, 170]   # Canal 1
    - [90, 190]   # Canal 2
    - [50, 150]   # Canal 3

data_queue:
  max_size: 10                  # Tamaño máximo de la cola de datos
  save_interval: 60              # Intervalo de guardado de datos en segundos

logging:
  log_file: "/home/raspberry-1/logs/pi1_logs.log"               # Archivo de logs para registrar las operaciones
  error_log_file: "/home/raspberry-1/logs/pi1_error_logs.log"   # Logs de errores
  max_size_mb: 5                                                # Tamaño máximo del archivo de logs en MB
  backup_count: 5                                               # Número de archivos de logs de respaldo
