logging:
  file: pi1.log
  level: DEBUG
mqtt:
  broker: localhost
  port: 1883
  topic: pi1/data
mux:
  address: 112
  channels:
  - channel: 0
    sensor_name: AS7265x_1
  - channel: 4
    sensor_name: AS7265x_2
  - channel: 7
    sensor_name: AS7265x_3
sensors:
  gain: 2
  integration_time: 200
  mode: 0
