system:
  enable_camera: false                # Raspberry Pi #1 no tiene cámara
  enable_sensors: true                # Sensores espectroscópicos AS7265x habilitados
  enable_sensor_leds: false           # Apagar LEDs de los sensores AS7265x
  enable_touch_screen: false          # No aplica a Raspberry Pi #1
  enable_mqtt: true                   # MQTT habilitado
  enable_greengrass: true             # AWS Greengrass habilitado
  enable_aws: true                    # Conexión a AWS habilitada
  enable_logging: true                # Logs habilitados
  enable_sensor_diagnostics: true     # Diagnósticos de sensores habilitados
  enable_mux_diagnostics: true        # Diagnósticos del MUX habilitados
  enable_auto_restart: false          # Reinicio automático habilitado
  enable_network_monitoring: true     # Monitoreo de red habilitado
  enable_detailed_logging: true       # Nivel detallado de logs
  enable_power_saving: true           # Modo de ahorro de energía
  read_calibrated_data: false          # Set to true to read calibrated data
  process_with_conveyor: true         # Procesar datos con cinta transportadora
  enable_conveyor_sync: true          # Sincronización con el conveyor habilitada

network:
  ethernet:
    ip: "192.168.1.145"           # Dirección IP estática para Ethernet
    gateway: "192.168.1.1"        # Puerta de enlace para Ethernet
  wifi:
    ssid: "Capstone"              # Nombre de la red Wi-Fi
    password: "Elefante"          # Contraseña de la red Wi-Fi
    ip: "192.168.2.145"           # Dirección IP estática para Wi-Fi
    gateway: "192.168.2.1"        # Puerta de enlace para Wi-Fi

data_queue:
  max_size: 10                  # Tamaño máximo de la cola de datos
  save_interval: 60              # Intervalo de guardado de datos en segundos

logging:
  level: DEBUG
  log_file: "/home/raspberry-1/logs/pi1_logs.log"               # Archivo de logs para registrar las operaciones
  error_log_file: "/home/raspberry-1/logs/pi1_error_logs.log"   # Logs de errores
  max_size_mb: 5                                                # Tamaño máximo del archivo de logs en MB
  backup_count: 5                                               # Número de archivos de logs de respaldo

mqtt:
  broker: localhost
  port: 1883
  topic: pi1/data
mux:
  address: 112
  channels:
  - channel: 0
    sensor_name: AS7265x_1
  - channel: 4
    sensor_name: AS7265x_2
  - channel: 7
    sensor_name: AS7265x_3
sensors:
  mode: 1                           # Modo de operación (0: Modo 0, 1: Modo 1, 2: Modo 2)
  integration_time: 300             # Tiempo de integración en ms
  gain: 3                           # Ganancia (0: 1x, 1: 3.7x, 2: 16x, 3: 64x)
  led_intensity: 128                # Intensidad de los LEDs (0-255)
  read_interval: 1                  # Intervalo de lectura en segundos
  enable_interrupts: true           # Habilitar interrupciones
  critical_temperature: 85          # Temperatura crítica en °C para el sensor
  power_saving: true                # Activar modo de ahorro de energía

greengrass:
  group_name: "Capstone-Group"   # Nombre del grupo de Greengrass
  functions:
    - name: "DetectPlasticType"   # Nombre de la función Lambda local
      arn: "arn:aws:lambda:region:account-id:function:DetectPlasticType"

aws:
  region: "us-east-1"                             # Cambia según tu región
  iot_core_endpoint: "your_aws_iot_core_endpoint" # Endpoint de AWS IoT Core
  iot_topics:
    sensor_data: "raspberry-1/sensor_data"                # Tópico para enviar datos de los sensores
    settings_update: "raspberry-1/settings_update"        # Tópico para recibir actualizaciones de configuración
  cert_path: "/certs/certificate.pem.crt"         # Certificado del cliente
  key_path: "/certs/private.pem.key"              # Llave privada
  ca_path: "/certs/AmazonRootCA1.pem"             # Certificado raíz de Amazon

mqtt:
  broker_address: 
  - "192.168.1.147"                               # Dirección IP del broker MQTT local (Ethernet Raspberry Pi #3)
  - "192.168.2.147"                               # Dirección IP del broker MQTT local (Wi-Fi Raspberry Pi #3)
  port: 1883                                      # Puerto del broker MQTT
  username: "raspberry-1"                                  # Usuario para el broker local
  password: "Elefante"                       # Contraseña para el broker local
  topics:
    sensor_data: "raspberry-1/sensor_data"                # Tópico para publicar datos de sensores
    settings_update: "raspberry-1/settings_update"        # Tópico para recibir actualizaciones de configuración
    alerts: "raspberry-1/alerts"                          # Tópico para enviar alertas

plastic_spectra:
  PET:
    Violet: 500
    Blue: 600
    Green: 700
    Yellow: 800
    Orange: 900
    Red: 1000
  HDPE:
    Violet: 450
    Blue: 550
    Green: 650
    Yellow: 750
    Orange: 850
    Red: 950
  LDPE:
    Violet: 480
    Blue: 580
    Green: 680
    Yellow: 780
    Orange: 880
    Red: 980
  PP:
    Violet: 430
    Blue: 530
    Green: 630
    Yellow: 730
    Orange: 830
    Red: 930
  PS:
    Violet: 470
    Blue: 570
    Green: 670
    Yellow: 770
    Orange: 870
    Red: 970
  PVC:
    Violet: 420
    Blue: 520
    Green: 620
    Yellow: 720
    Orange: 820
    Red: 920
