network:
  ethernet:
    ip: "192.168.1.137"           # Dirección IP estática para Ethernet
    gateway: "192.168.1.1"        # Puerta de enlace para Ethernet
  wifi:
    ssid: "Capstone"              # Nombre de la red Wi-Fi
    password: "Elefante"          # Contraseña de la red Wi-Fi
    ip: "192.168.2.11"            # Dirección IP estática para Wi-Fi
    gateway: "192.168.2.1"        # Puerta de enlace para Wi-Fi

mqtt:
  broker_addresses:
    - "192.168.1.147"             # Dirección IP del broker MQTT (Ethernet, Raspberry Pi #3)
    - "192.168.2.147"             # Dirección IP del broker MQTT (Wi-Fi, Raspberry Pi #3)
  port: 1883
  keepalive: 60 
  client_id: "Raspberry-2"
  topics:
    action: "valvula/accion"
    status: "valvula/estado"

i2c:
  bus: 1

sensors:
  pressure:
    addresses: [0x28, 0x29, 0x2A, 0x2B]

valves:
  relay_pins: [17, 27]

simulation:
  detection_interval: 5

logging:
  log_file: "/home/raspberry-2/logs/pi2_logs.log"               # Archivo de logs para registrar las operaciones
  error_log_file: "/home/raspberry-2/logs/pi2_error_logs.log"   # Logs de errores
  max_size_mb: 5                                                # Tamaño máximo del archivo de logs en MB
  backup_count: 5                                               # Número de archivos de logs de respaldo
