# Configuración específica para Raspberry Pi 2

network:
  ethernet:
    ip: "192.168.1.137"           # Dirección IP estática para Ethernet
    gateway: "192.168.1.1"        # Puerta de enlace para Ethernet
  wifi:
    ssid: "Capstone"              # Nombre de la red Wi-Fi
    password: "Elefante"          # Contraseña de la red Wi-Fi
    ip: "192.168.2.11"            # Dirección IP estática para Wi-Fi
    gateway: "192.168.2.1"        # Puerta de enlace para Wi-Fi

pressure_sensors:
  sensors:
    - i2c_address: 0x28          # Dirección I2C del sensor de entrada de la válvula 1
      name: "valve_1_inlet"
    - i2c_address: 0x29          # Dirección I2C del sensor de salida de la válvula 1
      name: "valve_1_outlet"
    - i2c_address: 0x2A          # Dirección I2C del sensor de entrada de la válvula 2
      name: "valve_2_inlet"
    - i2c_address: 0x2B          # Dirección I2C del sensor de salida de la válvula 2
      name: "valve_2_outlet"
  min_pressure: 0.0              # Presión mínima en PSI
  max_pressure: 25.0             # Presión máxima en PSI

valves:
  relay_module:
    addresses:
      valve_1: 1                # Número del relé para la válvula 1
      valve_2: 2                # Número del relé para la válvula 2
  trigger_level: "high"         # Nivel de disparo del relé (high o low)

greengrass:
  group_name: "Capstone-Group"  # Nombre del grupo de Greengrass
  functions:
    - name: "ValveControl"
      arn: "arn:aws:lambda:region:account-id:function:ValveControl"

aws:
  region: "us-east-1"                             # Cambia según tu región
  iot_core_endpoint: "your_aws_iot_core_endpoint"
  iot_topics:
    valve_control: "raspberry-2/valve_control"      # Tópico MQTT para control de válvulas
    settings_update: "raspberry-2/settings_update" # Tópico para actualizaciones de configuración
  cert_path: "/certs/certificate.pem.crt"  # Certificado del cliente
  key_path: "/certs/private.pem.key"       # Llave privada
  ca_path: "/certs/AmazonRootCA1.pem"      # Certificado raíz de Amazon

mqtt:
  broker_addresses:
    - "192.168.1.147"  # Dirección IP del broker MQTT (Ethernet, Raspberry Pi #3)
    - "192.168.2.147"  # Dirección IP del broker MQTT (Wi-Fi, Raspberry Pi #3)
  port: 1883
  username: "raspberry-2"
  password: "Elefante"
  topics:
    valve_control: "raspberry-2/valve_control"  # Tópico para recibir comandos de control de válvulas
    pressure_data: "raspberry-2/pressure_data"  # Tópico para publicar datos de presión

logging:
  log_file: "/logs/pi2_logs.log"                              # Archivo de logs para registrar las operaciones
  general_log_file: "/home/raspberry-2/logs/pi2_general.log"  # Archivo principal de logs generales
  error_log_file: "/home/raspberry-2/logs/pi2_error.log"      # Archivo para logs de errores
  sensors_log_file: "/home/raspberry-2/logs/pi2_sensors.log"  # Archivo para logs de sensores
  mqtt_log_file: "/home/raspberry-2/logs/pi2_mqtt.log"        # Archivo para logs de MQTT
  max_size_mb: 5                                              # Tamaño máximo del archivo en MB
  backup_count: 3                                             # Cantidad de archivos de respaldo
