network:
  ethernet:
    ip: "192.168.1.103"
    gateway: "192.168.1.1"
  wifi:
    ssid: "your_wifi_ssid"
    password: "your_wifi_password"
    ip: "192.168.1.104"
    gateway: "192.168.1.1"

sensors:
  pressure_sensor: "SparkFun Qwiic Micropresión"

valves:
  valve_1: "US Solid 1/4'' Stainless Steel Solenoid Valve"

aws:
  iot_core_endpoint: "your_aws_iot_core_endpoint"
  greengrass_group: "your_greengrass_group"
  iot_topic: "iot/pi2/data"
  cert_path: "/certs/certificate.pem.crt"
  key_path: "/certs/private.pem.key"
  ca_path: "/certs/AmazonRootCA1.pem"

logging:
  log_file: "logs/pi2_logs.log"
